import { useEffect, useMemo, useState } from 'react'
import { useAuth } from '@/features/auth'
import { addOrderStatusEvent, getVendorId, getVendorOrders, type VendorOrder, type VendorOrderStatus } from '../api/vendorDashboard.api'
import { Card, CardContent, CardHeader, CardTitle } from '@/shared/components/ui/card'
import { Badge } from '@/shared/components/ui/badge'
import { Button } from '@/shared/components/ui/button'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/shared/components/ui/tabs'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/shared/components/ui/table'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/shared/components/ui/select'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/shared/components/ui/alert-dialog'
import { formatNaira } from '@/shared/lib/currency'
import { toast } from 'sonner'

const next: Partial<Record<VendorOrderStatus, { label: string; status: VendorOrderStatus }>> = { pending: { label: 'Accept', status: 'accepted' }, accepted: { label: 'Start preparing', status: 'preparing' }, preparing: { label: 'Mark ready for pickup', status: 'ready_for_pickup' } }
type HistoryStatus = 'all' | 'delivered' | 'cancelled'
type HistoryPeriod = 'all' | '7-days' | '30-days'

export function Component() {
  const user = useAuth((state) => state.user)
  const [active, setActive] = useState<VendorOrder[]>([])
  const [history, setHistory] = useState<VendorOrder[]>([])
  const [busy, setBusy] = useState<string>()
  const [historyStatus, setHistoryStatus] = useState<HistoryStatus>('all')
  const [historyPeriod, setHistoryPeriod] = useState<HistoryPeriod>('all')
  const load = async () => { if (!user) return; const vendorId = await getVendorId(user.id); if (!vendorId) return; const [nextActive, nextHistory] = await Promise.all([getVendorOrders(vendorId, false), getVendorOrders(vendorId, true)]); setActive(nextActive); setHistory(nextHistory) }
  useEffect(() => { void load() }, [user])
  const change = async (order: VendorOrder, status: VendorOrderStatus) => { setBusy(order.id); try { await addOrderStatusEvent(order.id, status); toast.success(`Order ${status.replaceAll('_', ' ')}`); await load() } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to update order.') } finally { setBusy(undefined) } }
  const filteredHistory = useMemo(() => { const cutoff = historyPeriod === 'all' ? undefined : new Date(Date.now() - (historyPeriod === '7-days' ? 7 : 30) * 24 * 60 * 60 * 1000); return history.filter((order) => (historyStatus === 'all' || order.status === historyStatus) && (!cutoff || new Date(order.createdAt) >= cutoff)) }, [history, historyPeriod, historyStatus])
  const OrderCard = ({ order }: { order: VendorOrder }) => { const action = next[order.status]; return <Card><CardHeader className="flex-row items-center justify-between gap-3 space-y-0"><div><CardTitle className="text-base">{order.customerName}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{new Date(order.createdAt).toLocaleString()}</p></div><Badge>{order.status.replaceAll('_', ' ')}</Badge></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">{order.items.map((item) => `${item.quantity}× ${item.name}`).join(', ') || 'No item details'}</p><p className="font-semibold">{formatNaira(order.totalAmount * 100)}</p>{action ? <div className="flex gap-2"><Button disabled={busy === order.id} onClick={() => void change(order, action.status)}>{busy === order.id ? 'Saving…' : action.label}</Button>{order.status === 'pending' && <AlertDialog><AlertDialogTrigger asChild><Button variant="outline" disabled={busy === order.id}>Decline</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Decline this order?</AlertDialogTitle><AlertDialogDescription>The customer will be notified that the order cannot be fulfilled.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep order</AlertDialogCancel><AlertDialogAction className="bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={() => void change(order, 'cancelled')}>Decline order</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}</div> : <p className="text-sm text-muted-foreground">{order.status === 'ready_for_pickup' ? 'Waiting for a rider to be assigned.' : 'This order is now handled by delivery.'}</p>}</CardContent></Card> }
  return <div className="space-y-6"><div><h1 className="text-3xl font-semibold">Orders</h1><p className="text-muted-foreground">Process orders as they arrive.</p></div><Tabs defaultValue="active"><TabsList><TabsTrigger value="active">Active</TabsTrigger><TabsTrigger value="history">History</TabsTrigger></TabsList><TabsContent value="active" className="mt-4 grid gap-4">{active.length ? active.map((order) => <OrderCard key={order.id} order={order} />) : <Card><CardContent className="py-10 text-center text-muted-foreground">No active orders right now.</CardContent></Card>}</TabsContent><TabsContent value="history" className="mt-4 space-y-4"><div className="flex flex-wrap gap-3"><Select value={historyStatus} onValueChange={(value) => { if (value === 'all' || value === 'delivered' || value === 'cancelled') setHistoryStatus(value) }}><SelectTrigger><SelectValue placeholder="Status" /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="delivered">Delivered</SelectItem><SelectItem value="cancelled">Cancelled</SelectItem></SelectContent></Select><Select value={historyPeriod} onValueChange={(value) => { if (value === 'all' || value === '7-days' || value === '30-days') setHistoryPeriod(value) }}><SelectTrigger><SelectValue placeholder="Period" /></SelectTrigger><SelectContent><SelectItem value="all">All time</SelectItem><SelectItem value="7-days">Last 7 days</SelectItem><SelectItem value="30-days">Last 30 days</SelectItem></SelectContent></Select></div><Card><Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>Status</TableHead><TableHead>Date</TableHead><TableHead className="text-right">Total</TableHead></TableRow></TableHeader><TableBody>{filteredHistory.map((order) => <TableRow key={order.id}><TableCell>{order.customerName}</TableCell><TableCell><Badge variant="outline">{order.status}</Badge></TableCell><TableCell>{new Date(order.createdAt).toLocaleDateString()}</TableCell><TableCell className="text-right">{formatNaira(order.totalAmount * 100)}</TableCell></TableRow>)}{!filteredHistory.length && <TableRow><TableCell colSpan={4} className="h-24 text-center text-muted-foreground">No orders match these filters.</TableCell></TableRow>}</TableBody></Table></Card></TabsContent></Tabs></div>
}
